### PR TITLE
Class names rework

### PR DESCRIPTION
**Pull request by lifeart**
image

image

image

image

should fix https://github.com/lifeart/els-addon-typed-templates/issues/19

@emattias, @pdud, @NullVoxPopuli could you check stability of this branch on your projects?

Main features:

* improved quality of path highlighting
* updated components resolution logic
* updated controllers resolition logic
* meaningful class names in errors
* aruguments autocomplete in component-invocation usages (fix https://github.com/lifeart/els-addon-typed-templates/issues/19)
* type-checking for arguments in component-invocation usages

* typings from templates (Args) not yet used for arguments autocomplete

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
I get this:
image

**Comment by NullVoxPopuli** [comment]
Also, for a function where I don't care about arguments:
image

**Comment by NullVoxPopuli** [comment]
bunch of issues here, too
image

**Comment by NullVoxPopuli** [comment]
image
This is a helper that returns a function

**Comment by pdud** [comment]
It does appear to fix #19. It autocompletes arguments and also type checks them which is awesome :)

Screen Shot 2020-05-23 at 4 12 41 PM
Screen Shot 2020-05-23 at 4 22 09 PM

Minor nitpick it says `NumberInputComponentTemplate` not `NumberInput` as defined in the component.js class 🤷‍♂️ 

It does seem to underline the wrong item at times. See below. `this.isATypo` is not underlined but `@useCredits` is (which is valid).

Screen Shot 2020-05-23 at 4 35 40 PM

Thank you for all your work on this :)

**Comment by lifeart** [comment]
One more case to figure out:

image

**Comment by NullVoxPopuli** [comment]
that one might be a legit issue. my approach would be to push that into JS/TS so that you can use optional chaining

**Comment by NullVoxPopuli** [comment]
though, if hbs had optional chaining... :D

**Comment by lifeart** [comment]
@pdud different class names - it's expected behavour (for now), it's better comparing to one name :)

@pdud, @NullVoxPopuli  one more try?
looke like fixed:
- wrong location issue
- fixed incorrect args for template-only components (in some cases)
- fixed classic components invocation

**Comment by lifeart** [comment]
one more case to figure out:

image

fix (block params visibility)

**Comment by lifeart** [comment]
typings from templates (Args) now used for arguments autocomplete

**Comment by lifeart** [comment]
@pdud @NullVoxPopuli Looks like all found issues fixed. Could you recheck?

**Comment by pdud** [comment]
Working very well for me! We documented a lot of Args without marking them as optional and now we're being called out for it. 😂 (Which is good!)

Screen Shot 2020-05-24 at 10 18 51 AM

It's working better than ever for 3rd party add-ons for me :)

I see a commit for controllers autocomplete. I'm not sure what that includes. I expected the controller's properties/ actions to autocomplete for this but they are not.

Screen Shot 2020-05-24 at 10 27 00 AM

**Comment by lifeart** [comment]
@NullVoxPopuli regarding issues like:

image

I don't think it's possible to write same signature for different modifiers classes, so, we can add typings for it, or write kinda ast transform, to get function-like interface for modifiers and class-based helpers

**Comment by lifeart** [comment]
@pdud check `Unstable Ember Language Server` version, it should be `1.4.2` and controller should be class-based

**Comment by lifeart** [comment]
@emattias could you also check your case on this branch?

**Comment by NullVoxPopuli** [comment]
> I don't think it's possible to write same signature for different modifiers classes, so, we can add typings for it, or write kinda ast transform, to get function-like interface for modifiers and class-based helpers

the latest ember-modifiers has types: https://github.com/ember-modifier/ember-modifier/commits/master

looks like it hasn't be released yet though.

> can be fixed adding newline after comment

why is that needed? 

> Property 'defaultYield' does not exist on type 'KeyboardPress'. issue - fixable by adding defaultYield() function into component class (this is template-less component).

I should not need to add that ;)

> fa-icon issue should be fixed adding ts-ignore-line comment or
> <FaIcon @name='times' />

Converting to Angle brackets is long over due here :D thanks!

**Comment by lifeart** [comment]
@NullVoxPopuli 

`the latest ember-modifiers has types:` - it won't help, we transform one language to anover, and modifiers has funtion-like api, and we need to add one more ast transform for class-based modifiers to invoke it as function.

`why is that needed?` - we use comments for typings, lint rules, ignores, and multiline text comments near meaningfull nodes curently broke this logic.

`I should not need to add that ;)` - to cover it we need to add one more ast transform for components withour templates, to have "default" template.

but, defaultYeld() itself very powerful feature, and allow to specify typings for yeld blocks.

**Comment by NullVoxPopuli** [comment]
:-\ 

Until the default experience is supported, idk if els-addon-typed-templates will see mass adoption :-\

> add one more ast transform for class-based modifiers to invoke it as function.

We can just say that it's invokeable, yeah? the only thing we care about is the type args if they're present.

> near meaningfull nodes curently broke this logic.

is there any way to fix that?

> but, defaultYeld() itself very powerful feature, and allow to specify typings for yeld blocks.

but it seems like a requirement just to support els-addon-typed-template? idk

**Comment by lifeart** [comment]
@NullVoxPopuli 
`We can just say that it's invokeable, yeah? the only thing we care about is the type args if they're present.` - yes, but, how?

common modifier api is `function(node, [positional], hash)`, and its used in typed-templates,
class based modifiers need to be aligned somehow (it mean we need to detect class based and apply different transform), to get something like 
```ts
function classBasedModifierWrapper(node, params, hash) {
   return new ClassName().didInsert(node, params, hash);
}
```

`is there any way to fix that?` - yes, use babel templates instead of building typescript class from pure strings.

`but it seems like a requirement just to support els-addon-typed-template? idk` - yes, but I can't see another typing options for templates xD.

**Comment by NullVoxPopuli** [comment]
re: class modifiers:

I mean, can't we just ignore the fact it's a class and say it's a function that takes 0 to N number of arguments? unless it's written in typescript? and then parse out the the type argument? (the type arg passed to the super class)?

everything else:

🤔

**Comment by lifeart** [comment]
@NullVoxPopuli yes, we can, for now we just don't have strategy to figure out class it or not. It will be good to have "ast-based" detector to apply valid strategy.

**Comment by pdud** [comment]
@lifeart Controller is class based, and Unstable Ember Language Server version is 1.4.2 but it's still not working.

I am using pods? `app/pricing/{controller.js/template.hbs}`

**Comment by lifeart** [comment]
@pdud do you have 'podModulePrefix' in app config?

**Comment by pdud** [comment]
@lifeart I am not using `podModulePrefix`

I made that change, still didn't change things. (I confirmed the change was being run by outputting to console).

Let me know if there is something else I can do to help.

**Comment by emattias** [comment]
Cool stuff! This is what I have discovered (I colocate my js and hbs (and modules.scss) files, does that affect this?)

Only the arguments that are used in template show up as autocomplete when invocating a component:
CleanShot 2020-05-25 at 15 00 35@2x

this is `button.hbs`:

CleanShot 2020-05-25 at 15 02 38@2x

the reason that most arguments are written as local properties is that the component uses [ember-arg-types](https://github.com/jkusa/ember-arg-types):

CleanShot 2020-05-25 at 14 58 41@2x

If this typing can do what `ember-arg-types` does I think I will remove eat for this!

Other than arg autocomplete when invocating a component the main thing stopping me from using this is all the errors you get in components that havent been typed. I would like the typing to be opt in on a component to component basis. I'm working in a big code base and cant (and might not even need to) type everything in one go.

**Comment by lifeart** [comment]
@emattias collocation should work out of the box. Messages from screenshot not related to typed-templates (it's language server autocomplete).  Could you attach diagnostics warning for it?

Could you try autocomplete any component and after check typings? (we have lazy registry, and it will be initialized after autocomplete), PR to fix it - https://github.com/lifeart/ember-language-server/pull/126/files#diff-4fb20739dbe3cca0bae71f9c4ad1db4aR139

**Comment by emattias** [comment]
> @emattias collocation should work out of the box. Messages from screenshot not related to typed-templates (it's language server autocomplete).

hmm, ok those are the only autocomplete I get 🤔

> Could you attach diagnostics warning for it?

Sure, where/how do I get them?

> Could you try autocomplete any component and after check typings? (we have lazy registry, and it will be initialized after autocomplete), PR to fix it - [#126 (files)](https://github.com/lifeart/ember-language-server/pull/126/files#diff-4fb20739dbe3cca0bae71f9c4ad1db4aR139)

Are you saying it should work without that pr or that I should try that pr of els?

**Comment by lifeart** [comment]
`Are you saying it should work without that pr or that I should try that pr of els?` 
- it should work if you try autocomplete any component before

`hmm, ok those are the only autocomplete I get 🤔`
- try autocomplete last argument (instead of first, it may be an AST issue)

`Sure, where/how do I get them?`
- hover cursor on redlined code part

**Comment by emattias** [comment]
> `Are you saying it should work without that pr or that I should try that pr of els?`
> 
> * it should work if you try autocomplete any component before

I get the autocomplete for a components args in that components template. But not when invocating the component :/ I tried with another component:

CleanShot 2020-05-25 at 16 45 44@2x

I tried adding this to the template also. Did nothing :/

CleanShot 2020-05-25 at 16 47 07@2x


> `hmm, ok those are the only autocomplete I get 🤔`
> 
> * try autocomplete last argument (instead of first, it may be an AST issue)

No difference :/

> 
> `Sure, where/how do I get them?`
> 
> * hover cursor on redlined code part

that was my linter complaining, not related to this unfortunately :/

**Comment by lifeart** [comment]
@emattias do you have this addon loaded?
check console -> output tab + Unstable Ember Language Server selection in dropdown
image

**Comment by emattias** [comment]
CleanShot 2020-05-25 at 16 53 26@2x

**Comment by emattias** [comment]
Could this be a clue to whats going on?

CleanShot 2020-05-25 at 16 57 31@2x

**Comment by lifeart** [comment]
@emattias looks like yarn/npm cache, this issue already fixed in this branch, could you try to checkout this branch using hash? https://github.com/lifeart/els-addon-typed-templates/pull/20/commits/a964b5d191350da57271aca7107ecafa4beac641

**Comment by emattias** [comment]
Now its working! 🎉

**Comment by emattias** [comment]
CleanShot 2020-05-25 at 17 57 12@2x

This is kind of annoying. Is there a way to make it interpret the argument value as its exact string `large` instead of `string` as it is here? That way you can type the argument to suggest the different allowed values for that argument.

Or is there another way to make vscode suggest the allowed values of an argument that takes a limited set of strings?

This is how the `@size` argument is typed:

```js
/**
 * @typedef {'large' | 'small'} sizes
 * @typedef {Object} Args
 * @property {sizes} size;
 * @extends Component<Args>
 */
export default class Button extends Component {
```

**Comment by lifeart** [comment]
@emattias try https://github.com/lifeart/els-addon-typed-templates/pull/20/commits/b7a456543415da00c672e7d8e476129f59f546aa

**Pull request merged**
