### PR TITLE
Properly handle Ember.Array in each helper

### LINKED ISSUE #74: Unable to determine yield type for `#each` with Ember Data `AsyncHasMany`
Shows unknown instead of the correct type.

(I plan to investigate this more soon.)

### PR DESCRIPTION
**Pull request by wagenet**
Fixes #74

### CODE REVIEW

**Comment by lifeart** [comment]
@wagenet thank you!

**Comment by lifeart** [comment]
Published `els-addon-typed-templates@4.2.4`

**Comment by wagenet** [comment]
@lifeart obviously, it wasn't a blocker but I noticed that there are no tests for these. Is it worth trying to add some or does it turn out to not really be practical?

**Comment by lifeart** [comment]
@wagenet I'm not against tests

**Pull request merged**
